### ISSUE TITLE
[Quais] - Look into the contract deployment issue, and fix SALT

### ISSUE THREAD

**Issue by mibuono** [dominant-strategies/quais-6.js#55] opened 2024-03-15 14:30 UTC
Background:
We tried to pregrind the contract address for where it is doing to be deployed and added to a data field for a transaction.  Once we do that, GoQuai recognizes the data field as a different destination address than what was provided on the quais side.

Our hunch is it is the salt not being done correctly.

Goals here are to:
Be able to pass a destination address and it match in quais and goquai

**Comment by rileystephens28** [comment] 2024-04-11 19:57
@alejoacosta74 did some discovery on this and we have concluded that the issue is most likely caused by incorrectly encoding data before hashing and signing which is leading to an incorrect computation of `from` address from transaction signature. Closing this issue and opening others related to findings.

**Closed by rileystephens28** 2024-04-11 19:57 UTC
Labels: bug, Quais
